### PR TITLE
Fixed "no_OPTION" in register & updated docs.

### PR DESCRIPTION
**Pull request by SailingYYC**
The `for` loop uses a named variable but the conditional in the loop uses `$_`.

Strangely enough one of my apps passes this without complaint, the other warns of 3 uses of undef in a concatenation.

### CODE REVIEW

**Comment by SailingYYC** [comment]
@benvanstaveren, Any chance you can version bump `master` to `v1.16` and push out to CPAN?

Most appreciated,
Colin

**Comment by benvanstaveren** [comment]
Ugh, I knew I was forgetting something!

**Comment by benvanstaveren** [comment]
Pushed as 1.16

**Comment by SailingYYC** [comment]
No worries and thanks. I think that closes off the other 2 open issues as well.

**Pull request merged**
